### ISSUE TITLE
The `gpt-synthesizer`command produces this error.

### ISSUE THREAD

**Issue by razsa** [RoboCoachTechnologies/GPT-Synthesizer#10]
gpt-synthesizer
/Users/<>/Documents/dev/GPT-Syn/.venv/lib/python3.11/site-packages/langchain/chat_models/__init__.py:31: LangChainDeprecationWarning: Importing chat models from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.chat_models import ChatOpenAI`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
/Users/<>/Documents/dev/GPT-Syn/.venv/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: The class `langchain_community.chat_models.openai.ChatOpenAI` was deprecated in langchain-community 0.0.10 and will be removed in 0.2.0. An updated version of the class exists in the langchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import ChatOpenAI`.
  warn_deprecated(
Traceback (most recent call last):
  File "/Users/<>/Documents/dev/GPT-Syn/.venv/bin/gpt-synthesizer", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/<>/Documents/dev/GPT-Syn/.venv/lib/python3.11/site-packages/gpt_synthesizer/main.py", line 31, in main
    comp_prompt, comp_parser = get_comp_prompt()
                               ^^^^^^^^^^^^^^^^^
  File "/Users/<>/Documents/dev/GPT-Syn/.venv/lib/python3.11/site-packages/gpt_synthesizer/prompt.py", line 22, in get_comp_prompt
    parser = get_comp_parser()
             ^^^^^^^^^^^^^^^^^
  File "/Users/<>/Documents/dev/GPT-Syn/.venv/lib/python3.11/site-packages/gpt_synthesizer/parser.py", line 16, in get_comp_parser
    return PydanticOutputParser(pydantic_object=CompList)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<>/Documents/dev/GPT-Syn/.venv/lib/python3.11/site-packages/langchain_core/load/serializable.py", line 120, in __init__
    super().__init__(**kwargs)
  File "/Users/<>/Documents/dev/GPT-Syn/.venv/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for PydanticOutputParser
pydantic_object
  subclass of BaseModel expected (type=type_error.subclass; expected_class=BaseModel)

**Comment by saeedshamshiri** [comment]
Thanks for the feedback. We will get back to you shortly.

**Comment by RoboCoachian** [comment]
Hi @razsa,
This is issue seems to be related to the recent changes in LangChain code base. consider setting your LangChain version to `0.0.320`.

Please let us know if that solves your issue. Thanks!
